Repository SUSE/doc-ses, pull requests merged in 2019-12, with the labels that each got.

#133 Added a tip on monitoring cluster nodes' status during upgrade (bsc#1154568)
  xml/admin_ceph_upgrade.xml
  xml/deployment_docupdates.xml
Labels: backport to ses6

#110 Creating new monitoring and alerting chapter (BSC#1138864)
  images/src/odg_masters/bloom-filter.odg
  images/src/odg_masters/ceph_admin_ha1.ofg.odg
  images/src/odg_masters/crush-firstn-indep.odg
  images/src/odg_masters/crush-step.odg
  images/src/odg_masters/data-structure-example.odg
  images/src/odg_masters/device_classes.odg
  images/src/odg_masters/rados-structure.odg
  images/src/png/crush-step.png
  images/src/png/migration-target.png
  images/src/png/rbd-mirror-daemon.png
  images/src/png/rbd-mirror-image.png
  images/src/png/rbd-mirror-images-status.png
  images/src/png/rbd-mirror-pool-list-1.png
  images/src/png/rbd-mirror-pool-list.png
  images/src/png/rbd-mirror-pool-mode.png
  images/src/png/rbd-mirror-pool-peer.png
  images/src/png/rbd-mirror-pool.png
  xml/admin_gui_dashboard.xml
  xml/admin_monitoring_alerting.xml
  xml/admin_operating_monitor.xml
  xml/book_storage_admin.xml
  xml/entity-decl.ent
  xml/ses_glossary.xml
Labels: backport to ses6

#142 Adding additional information on non-SUSE OpenStack distros (BSC#1158222)
  xml/admin_about.xml
Labels: backport to ses5, backport to ses6

#138 Section about @/var/lib/ceph subvolume now covers all scenarios (bsc#1155450)
  xml/admin_ceph_tips.xml
  xml/admin_install_salt.xml
Labels: backport to ses6, update docupdates

#145 Updating the "ceph mds set" command (BSC#1157885)
  xml/admin_ceph_cephfs.xml
Labels: backport to ses6

#148 Additional software channels (bsc#1158106)
  xml/admin_ceph_upgrade.xml
Labels: backport to ses6
