Repository SUSE/doc-ses, pull requests merged in 2019-11, with the labels that each got.

#129 Updated product and OS numbers for SES4 & SES5.5
  xml/entity-decl.ent
Labels: update online

#120 Adding new intro chap for Arm architecture (BSC#1154813)
  xml/deployment_hwrecommend.xml
  xml/entity-decl.ent
Labels: backport to ses6

#128 Included a Japanese translation about Ceph contributors (bsc#1154135)
  ja/xml/contributors.xml
Labels: update online

#125 Merged ceph changelogs into 1 file (bsc#1155412)
  xml/admin_docupdates.xml
  xml/book_storage_admin.xml
  xml/book_storage_deployment.xml
  xml/ceph_maintenance_updates.xml
  xml/deployment_docupdates.xml
  xml/maintenance_updates_admin.xml
Labels: backport to ses6

#127 Run 'rpmconfigcheck' after each node upgrade (jsc#SES-348)
  xml/admin_ceph_upgrade.xml
  xml/deployment_docupdates.xml
Labels: backport to ses6

#108 Introduced an automatic way of migrating a node during cluster upgrade (bsc#1154438)
  xml/admin_ceph_upgrade.xml
  xml/deployment_docupdates.xml
Labels: backport to ses6, do not merge

#132 Re-worded minimum requirements for OSDs (bsc#1155931)
  xml/deployment_hwrecommend.xml
Labels: backport to ses5, backport to ses6, bug

#124 Adding new validating OSD LVM metadata section (BSC#1152333)
  xml/admin_saltcluster.xml
Labels: backport to ses6

#137 added a new table with description of columns
  xml/admin_operating_pools.xml
Labels: backport to ses6, update docupdates
