Repository SUSE/doc-ses, pull requests merged in 2020-03, with the labels that each got.

#196 CHAP authentication username/password update (bsc#1165729)
  xml/deployment_iscsi.xml
Labels: backport to ses5, backport to ses6

#194 Getting Ganesha exports (bsc#1164497)
  xml/admin_nfsganesha.xml
  xml/entity-decl.ent
Labels: backport to ses6

#197 Purging is no longer required, remove 4th step (BSC#1165658)
  xml/admin_ceph_gateway.xml
Labels: backport to ses6

#198 Adding note for restart checks (BSC#1165037)
  xml/admin_operating_services.xml
Labels: backport to ses6

#201 Adding new sections and files to bp guide
  xml/book_storage_bp_troubleshooting.xml
  xml/bp_troubleshooting_logging.xml
  xml/bp_troubleshooting_monitors.xml
  xml/bp_troubleshooting_networking.xml
  xml/bp_troubleshooting_objectstorage.xml
  xml/bp_troubleshooting_osds.xml
  xml/bp_troubleshooting_pgs.xml
  xml/bp_troubleshooting_tips.xml
  xml/bp_troubleshooting_troubleshooting.xml
Labels: do not merge

#204 Fixing portblock resource section (BSC#1165745)
  xml/deployment_ganesha.xml
Labels: bug

#208 Add extra info on ganesha ha deepsea (BSC#1166385)
  xml/deployment_ganesha.xml
Labels: backport to ses5

#206 Moving step 4 to step 11 to improve flow of procedure (BSC#1166375)
  xml/admin_install_salt.xml
Labels: backport to ses6

#205 Updating us-east-1 and removing duplicate step (BSC#1166095)
  xml/admin_ceph_gateway.xml
Labels: backport to ses6

#215 Adding chown instruction for more user friendly exp (BSC#1166417)
  xml/admin_install_salt.xml
Labels: backport to ses6

#219 Changing drivegroups intro text - Closes #217
  xml/admin_install_salt.xml
Labels: backport to ses6
