Repository SUSE/doc-ses, pull requests merged in 2020-11, with the labels that each got.

#761 remove deactivate step
  xml/admin_ceph_cephfs.xml
Labels: bug

#762 Remove mds_standby_for_rank
  xml/admin_ceph_cephfs.xml
Labels: backport to ses6, bug

#784 Add section on querying the default container images
  xml/bp_troubleshooting_cephadm.xml
Labels: SES7

#795 Made the dashboard chapter a book part
  xml/admin_caasp_crd.xml
  xml/admin_gui_dashboard.xml
  xml/book_storage_admin.xml
  xml/dashboard_about.xml
  xml/dashboard_cluster.xml
  xml/dashboard_ganesha.xml
  xml/dashboard_manual_config.xml
  xml/dashboard_mds.xml
  xml/dashboard_ogws.xml
  xml/dashboard_pools.xml
  xml/dashboard_rbds.xml
  xml/dashboard_user_cmdline.xml
  xml/dashboard_users.xml
  xml/dashboard_webui.xml
  xml/docupdates.xml
  xml/manager_modules.xml
Labels: update docupdates
