Repository SUSE/doc-ses, pull requests merged in 2020-01, with the labels that each got.

#134 Made network recommendations more specific (bsc#1156631)
  xml/deployment_docupdates.xml
  xml/deployment_hwrecommend.xml
Labels: backport to ses6, do not merge

#152 Fixing links to suse.com/documentation to correct URL (noref)
  xml/admin_ceph_gateway.xml
  xml/admin_ceph_iscsi.xml
  xml/admin_ceph_kvm.xml
  xml/admin_ceph_tips.xml
  xml/admin_ceph_troubleshooting.xml
  xml/admin_ceph_upgrade.xml
  xml/admin_docupdates.xml
  xml/admin_install_salt.xml
  xml/admin_intro.xml
  xml/admin_nfsganesha.xml
  xml/admin_saltcluster.xml
  xml/common_intro_available_doc_i.xml
  xml/common_intro_feedback_i.xml
  xml/containerized-kubernetes.xml
  xml/deployment_admin_ha.xml
  xml/deployment_cifs.xml
  xml/deployment_docupdates.xml
  xml/deployment_ganesha.xml
Labels: backport to ses5, backport to ses6

#153 'salt osd.retain' is obsoleted (bsc#1160219)
  xml/admin_saltcluster.xml
Labels: backport to ses6

#151 Adding new portblock resource section (BSC#1123188)
  xml/deployment_ganesha.xml
Labels: backport to ses5, backport to ses6

#155 Updated unclear strings with understandable alternatives
  xml/admin_ceph_cephfs.xml
  xml/admin_ceph_datamgm.xml
  xml/admin_ceph_upgrade.xml
  xml/admin_gui_dashboard.xml
  xml/admin_install_salt.xml
  xml/admin_saltcluster.xml
  xml/ceph_maintenance_updates.xml
  xml/ceph_prompts.xml
  xml/deployment_cifs.xml
Labels: backport to ses5, backport to ses6

#156 Removing specific instances of x86 in favor of <replaceable> (BSC#1155012)
  xml/admin_ceph_gateway.xml
  xml/admin_ceph_iscsi.xml
  xml/admin_ceph_libvirt.xml
  xml/deployment_hwrecommend.xml
  xml/deployment_iscsi.xml
Labels: backport to ses6

#150 Overriding default NTP settings (bsc#1160080)
  xml/admin_ceph_troubleshooting.xml
  xml/admin_install_salt.xml
Labels: backport to ses5, backport to ses6

#158 Run upgrade.check runner to verify upgrade conditions (jsc#SES-356)
  xml/admin_ceph_upgrade.xml
Labels: backport to ses6

#157 Aligned list of pool values (bsc#1113674)
  xml/admin_ceph_erasure.xml
  xml/admin_operating_pools.xml
Labels: backport to ses5, backport to ses6

#149 Creating new Alert Troubleshooting section (JSC#667)
  xml/admin_monitoring_alerting.xml
  xml/app_alerting.xml
  xml/book_storage_admin.xml
Labels: backport to ses6, do not merge

#160 Fixed unclear localization strings, round 2
  xml/admin_ceph_datamgm.xml
  xml/admin_ceph_gateway.xml
  xml/admin_operating_monitor.xml
  xml/ceph_maintenance_updates.xml
  xml/manager_modules.xml
Labels: backport to ses6

#161 Added missing descriptions of Dashboard's performance widgets (bsc#1160971)
  xml/admin_gui_dashboard.xml
Labels: backport to ses6

#162 Prompt fixes in the upgrade chapter (bsc#1161801)
  xml/admin_ceph_upgrade.xml
Labels: backport to ses6

#163 Admin network not supported (bsc#1067112)
  xml/deployment_hwrecommend.xml
Labels: backport to ses5, backport to ses6
