Repository SUSE/doc-ses, pull requests merged in 2020-12, with the labels that each got.

#763 Add note regarding virtual .snap dir
  xml/admin_ceph_cephfs.xml
Labels: enhancement

#743 Update admin_ceph_upgrade.xml
  xml/admin_ceph_upgrade.xml
Labels: SES7, bug

#785 Re-order nfs-ganesha deployment guide flow
  xml/admin_nfsganesha.xml
Labels: SES7

#836 Fix Alertmanager configuration example
  xml/admin_monitoring_alerting.xml
Labels: bug
