Repository SUSE/doc-ses, pull requests merged in 2020-08, with the labels that each got.

#432 Updated operating Ceph services to not use DeepSea anymore (gh#366)
  xml/admin_operating_services.xml
  xml/bp_troubleshooting_tips.xml
Labels: SES7

#452 Removing deepsea notes from troubleshooting guide
  xml/bp_troubleshooting_tips.xml
Labels: do not merge

#457 rework HA/standalone Samba service documentation
  xml/deployment_cifs.xml
Labels: backport to ses6

#455 Specify security and realm smb.conf parameters (bsc#1157369)
  xml/deployment_cifs.xml
Labels: backport to ses6
