Repository SUSE/doc-ses, pull requests merged in 2020-04, with the labels that each got.

#222 minor Samba gw admin fixes
  xml/deployment_cifs.xml
Labels: backport to ses5, backport to ses6

#212 Converting the Tuning Guide from adoc to XML
  images/src/png/yast_ring_buffers.png
  xml/authors-tuning.xml
  xml/book_storage_tuning.xml
  xml/tuning-appendix.xml
  xml/tuning-architecture.xml
  xml/tuning-ceph-tiered-storage.xml
  xml/tuning-ceph-tuning.xml
  xml/tuning-intro.xml
  xml/tuning-lvmcache.xml
  xml/tuning-os-tuning.xml
Labels: backport to ses6

#224 deployment_smb: kernel backed share instructions
  xml/deployment_cifs.xml
Labels: backport to ses6

#243 Correcting service names - Closes #241
  xml/deployment_cifs.xml
Labels: backport to ses6

#237 Adding note about disk encryption exception to upgrade Closes #235
  xml/admin_ceph_upgrade.xml
Labels: do not merge, update docupdates
