Repository SUSE/doc-ses, pull requests merged in 2020-07, with the labels that each got.

#414 No need for LTSS repositories (bsc#1173306)
  xml/admin_install_salt.xml
Labels: SES5, bug

#415 Remove LTSS repositories before migration (bsc#1173306)
  xml/admin_ceph_upgrade.xml
Labels: SES6, bug

#418 Adding note about recommended DB sizing - Closes#416
  xml/tuning-architecture.xml
Labels: backport to ses6

#422 Note to removing OSDs (gh#420)
  xml/admin_saltcluster.xml
Labels: SES7
