Repository SUSE/doc-ses, pull requests merged in 2020-02, with the labels that each got.

#168 Shutdown and start of the whole cluster (bsc#1126210)
  xml/admin_operating_services.xml
Labels: backport to ses6

#169 Adding new note defining log action (BSC#1157612)
  xml/admin_nfsganesha.xml
Labels: backport to ses5

#173 Remove ambiguity of "custom config" (BSC#1162300)
  xml/admin_saltcluster.xml
Labels: backport to ses6

#174 Adding straw to straw2 verification step (BSC#1162242)
  xml/admin_ceph_upgrade.xml
Labels: backport to ses6

#176 Adding new "too_many_pgs" troubleshooting chapter (BSC#1112924)
  xml/admin_ceph_troubleshooting.xml
Labels: backport to ses5, backport to ses6

#177 Adding important note for keyring compromise (BSC#1112917)
  xml/admin_cephx.xml
Labels: backport to ses5, backport to ses6

#171 Shutdown and starting of whole Ceph cluster (bsc#1126210)
  xml/admin_operating_services.xml
Labels: backport to ses5

#165 Added pool migration limitations (bsc#1140080)
  xml/admin_operating_pools.xml
Labels: backport to ses5, backport to ses6

#179 SMB gatways in SLE-HA setup enhancements (bsc#1123896)
  xml/deployment_cifs.xml
Labels: backport to ses5, backport to ses6

#181 Removing duplicated (and incorrect) mds point (BSC#1163814)
  xml/deployment_cephfs.xml
Labels: backport to ses6

#180 Fixing minor typo: Missing colon in URL (BSC#1163987)
  xml/admin_monitoring_alerting.xml
Labels: backport to ses6

#183 Adding cross-link to remove mds instruction (BSC#1163816)
  xml/deployment_cephfs.xml
Labels: backport to ses6

#184 ceph.maintenance.upgrade runner not yet supported (bsc#1158449)
  xml/admin_saltcluster.xml
Labels: backport to ses6

#182 Adding password update to upgrade procedure (BSC#1163716)
  xml/admin_ceph_upgrade.xml
  xml/deployment_iscsi.xml
Labels: backport to ses6

#185 Resolving dependency conflict for IGW (bsc#1163054)
  images/src/png/igw_pkg_conflict.png
  xml/admin_ceph_upgrade.xml
Labels: backport to ses6

#186 Adding autoscale docs for pg_num (BSC#1163693)
  xml/admin_ceph_datamgm.xml
  xml/admin_ceph_troubleshooting.xml
Labels: backport to ses6

#172 Adding more content for networking overview section (JSC#1116)
  images/src/png/network-overview-diagram.png
  xml/deployment_hwrecommend.xml
Labels: backport to ses6
