Repository SUSE/doc-ses, pull requests merged in 2020-10, with the labels that each got.

#644 cephcluster.yaml docs + hardware updates
  xml/deploy_caasp.xml
Labels: do not merge, in progress

#597 Update troubleshooting tips about orphaned partitions
  xml/bp_troubleshooting_tips.xml
Labels: SES7, bug

#674 Remove optional <placement_string> parameter
  xml/deploy_cephadm.xml
Labels: bug, do not merge

#691 Reflect #472 to JPN version
  ja/xml/admin_saltcluster.xml
Labels: jap-trans

#695 SES6: Remove literal in screen
  xml/manager_modules.xml
Labels: bug

#720 Add explanation to customize monitoring images
  xml/admin_monitoring_alerting.xml
  xml/deploy_cephadm.xml
Labels: SES7
