Repository SUSE/doc-ses, pull requests merged in 2021-04, with the labels that each got.

#915 Removed appendix with documentation updates (#914)
  xml/book_storage_admin.xml
  xml/book_storage_deployment.xml
  xml/book_storage_rook.xml
  xml/book_storage_security.xml
  xml/book_storage_troubleshooting.xml
  xml/book_storage_windows.xml
  xml/docupdates.xml
Labels: SES7

#917 Added rgw_s3_auth_use_ldap option description (#909)
  xml/admin_ceph_gateway.xml
Labels: backport to ses6

#919 doc: adding addendum deep scrub
  xml/admin_saltcluster.xml
Labels: backport to ses6

#920 Update Grafana container tag version
  xml/admin_monitoring_alerting.xml
Labels: SES7

#925 Update remnant of previous Grafana version
  xml/admin_ceph_upgrade.xml
Labels: SES7

#922 Revise adoption of monitoring services
  xml/admin_ceph_upgrade.xml
Labels: bug
