Repository SUSE/doc-ses, pull requests merged in 2021-01, with the labels that each got.

#849 Moving scrub-related options to [global] section (bsc#1162543)
  xml/admin_ceph_upgrade.xml
  xml/admin_install_salt.xml
Labels: SES6

#854 deployment_smb: recommend kernel backed shares
  xml/deployment_cifs.xml
Labels: SES7, backport to ses6

#852 cephadm user needs sudo
  xml/deploy_cephadm.xml
Labels: SES7
