Repository SUSE/doc-ses, pull requests merged in 2021-11, with the labels that each got.

#965 Fixed typo (#964)
  xml/admin_ceph_datamgm.xml
Labels: backport to ses7

#969 Update Node-Exporter version
  xml/admin_monitoring_alerting.xml
Labels: SES7

#970 Fixed commands generating dashboard certificates (bsc#1192317)
  xml/dashboard_manual_config.xml
Labels: backport to ses6, backport to ses7
