Repository SUSE/doc-ses, pull requests merged in 2022-03, with the labels that each got.

#991 Adapt Prometheus Alertmanager SNMP documentation to new upstream solution
  xml/admin_monitoring_alerting.xml
Labels: enhancement, SES7

#994 Restart MGR after configuring grafana certs (#990)
  xml/admin_monitoring_alerting.xml
Labels: backport to ses7

#998 Adding exceptions for self-signed SSL certificates in the Ceph Dashboard
  xml/bp_troubleshooting_dashboard.xml
Labels: enhancement, SES7, dashboard

#997 Add a note to 'Debugging the Ceph Dashboard flag'
  xml/bp_troubleshooting_dashboard.xml
Labels: enhancement, SES7, dashboard

#1000 Updated commands for setting OGW credentials
  xml/dashboard_manual_config.xml
Labels: backport to ses7
